// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accuWeather": {
            "get": {
                "description": "Получить информацию по координатам",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить информацию о погоде из AccuWeather",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Широта",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Долгота",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WeatherModel"
                        }
                    }
                }
            }
        },
        "/openWeather": {
            "get": {
                "description": "Получить информацию по координатам",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить информацию о погоде из OpenWeather",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Широта",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Долгота",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WeatherModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.WeatherModel": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "main": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pressure": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                },
                "temp": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WeatherCaravan",
	Description:      "Simple server for work with weather data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
